topic_relay_odom:
  ros__parameters:
    input_topic: /loc/gazebo
    msg_type: odometry
    output_topic: /odom
    parent_frame: odom
    child_frame: base_link
    publish_tf: odom_base

topic_relay_loc:
  ros__parameters:
    input_topic: /loc/slam
    msg_type: pose
    output_topic: /loc
    parent_frame: map
    child_frame: base_link
    publish_tf: none
